### ISSUE TITLE
Can not find xmlrpc.

### ISSUE THREAD

**Issue by JessicaPuebla** [eschnou/storytlr#100]
Hi. I can not install storytlr on my server. When wizard starts at Requirements Check I have this only problem: 

Can not find xmlrpc.

![image](https://cloud.githubusercontent.com/assets/17030278/18997731/5b4b5ff8-86fb-11e6-982d-cd75b9f9b6cf.png)

Help please.

**Comment by jmhobbs** [comment]
Your host doesn't have the xml-rpc extension installed/enabled.  You will need to install it if you have access, or request that your host install it for you.

http://php.net/manual/en/book.xmlrpc.php

**Comment by JessicaPuebla** [comment]
Thanks. Your informations helped me to fix the problem.
