### ISSUE TITLE
storytlr still active?

### ISSUE THREAD

**Issue by petrk94** [eschnou/storytlr#103]
Hello I have seen that storytlr is since longer time not active.
Is the project dead?

**Comment by eschnou** [comment]
Storytlr is not being actively developed but still used by many as their favorite homepage. Yet, I'm always happy to merge and review interesting pull requests.

**Comment by petrk94** [comment]
Maybe it were a good idea to write in the README.md to show that its not longer in active development. Using today a software which is 7 years old is not really safety I guess :/ just my opinion.
Thanks for your answer.
