### ISSUE TITLE
Cant start install

### ISSUE THREAD

**Issue by ziyafenn** [eschnou/storytlr#16]
After creating db and extracting stirytlr files, i open from browser link where placed storytlr files, install wizard dont start, 
There is error: Could not find the config.ini configuration file. Please verify your setup.

**Comment by eschnou** [comment]
From the error you describe; it looks like you are not working with 1.0 but something like 0.9.3. Are you sure you did download the last release ? Maybe we forgot to change a link somewhere.

To verify the release number, just look inside the README file in the root folder.

Thanks

**Comment by ziyafenn** [comment]
yeah. you are right, im using old relase. thanks, i fdownloaded last release!
