### ISSUE TITLE
Short urls not working in 1.0

### ISSUE THREAD

**Issue by julienferla** [eschnou/storytlr#17]
when I post a thing in my Storytlr it generate a short url and tweet the new post

for exemple look at this tweet:
http://twitter.com/julienhidch/status/21906673473

but the short url redirect on a blank page.
have any idea why ?

thank your for help

**Comment by eschnou** [comment]
Blank page probably means some PHP error somewhere. Can you please:
- set debug=1 in protected/config/config.ini ? Let us know the error message if you see one.
- look at protected/logs/applicationException.log for any errors

Thanks

**Comment by julienferla** [comment]
here it is the message on the blank page after debug = 1

Fatal error: Call to undefined method Stuffpress_Application::getDomain() in /home/juliench/public_html/protected/application/admin/models/ShortUrl.php on line 95

**Comment by eschnou** [comment]
Thanks Julien. I found the issue. It is indeed a bug, I'll fix it and release 1.0.1 as soon as possible. Sorry for that.

In the meanwhile, you can repleace the file protected/library/Stuffpress/Application.php
with this one: http://github.com/storytlr/core/raw/feature-rest-api/protected/library/Stuffpress/Application.php

It should do the trick.

**Comment by julienferla** [comment]
Thank you for the quick fix, Yes it work with this new file !
