### ISSUE TITLE
Short URL links not working

### ISSUE THREAD

**Issue by dueyfinster** [eschnou/storytlr#19]
This was posted to Twitter:
Shared the link: Chrome to iPhone - Google Chrome extension gallery http://neil.grogan.ie/s/7mpz

Link is a dud, should point to:
http://neil.grogan.ie/entry/chrome-to-iphone---google-chrome-extension-gallery-1-2.html

I think this is a bug?

**Comment by dueyfinster** [comment]
Sorry duplicate!

**Comment by eschnou** [comment]
:-) No worries, maybe i should not close issues as long as the fix is not in the release, to avoid people missing them.
