### ISSUE TITLE
Storytlr requires PHP Curl, which can not be found.

### ISSUE THREAD

**Issue by ziyafenn** [eschnou/storytlr#2]
When i want to install storytlr on my localhost, after configuration of config.ini , i get this error when i open index.php.
help!
and also, there is templates for storytlr ?)
thanks!

**Comment by eschnou** [comment]
You need to have the PHP Curl module installed. if you are on ubuntu, doing "apt-get install php-curl" will be enough. It will be different on other systems. Note that you also need other dependencies: mcrypt, pdo and pdo_mysql.
