### ISSUE TITLE
What happened here?

### ISSUE THREAD

**Issue by websurf** [eschnou/storytlr#20]
I recently installed storytlr on my site to see how it works. I installed it and went to the live site and this appeared http://nicks-blog.net/storytlr/index.php . Does anyone know how this happened?

**Comment by jmhobbs** [comment]
It looks like the application base is set wrong.

```
<base href="http://nicks-blog.net/storytlr/index.php/" />
```

should be

```
<base href="http://nicks-blog.net/storytlr/" />
```

**Comment by websurf** [comment]
How to I change this?

**Comment by jmhobbs** [comment]
Good question!  In your protected/config/config.ini, what are your values for web.host and web.path?  I'm guessing your web.path is something like this:
    web.path=/index.php/
When it should be:
    web.path=/
