### ISSUE TITLE
Upgrading from 0.9.3 with custom plugins to 1.0.1 fails

### ISSUE THREAD

**Issue by awafaa-zz** [eschnou/storytlr#21]
On my 0.9.3 install I had added the github plugin amongst others.  When I followed the instructions for upgrading I get the following error:

Error running database upgrade script:
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '"""DROP TABLE IF EXISTS `github_data`' at line 1

Any ideas? thanks.

**Comment by eschnou** [comment]
Can you delete that first line in protected/install/update/001/plugin_github.sql - It seems it should not be there :-)

**Comment by eschnou** [comment]
I have removed that weird line from the script and updated release 1.0.1, hope it solves your issue. Let us know ! Thx Andrew.

**Comment by awafaa-zz** [comment]
Excellent thanks!!

Removing the first line in /protected/install/database/update/001/plugin_github.sql fixed it
