### ISSUE TITLE
Can not find PDO.

### ISSUE THREAD

**Issue by waaghals** [eschnou/storytlr#25]
Phpinfo() says it is enabled.

Do I need to set a path somewhere or is this a bug?

**Comment by jmhobbs** [comment]
Do you have the MySQL PDO driver installed?

Is this error in the installer or elsewhere?

**Comment by waaghals** [comment]
The error is in the installer during the requirements check.

Yes the mysql, odbc and sqlite drivers are enabled for PDO

**Comment by jmhobbs** [comment]
Ok, can you provide more info about the install?  Versions and stuff?

A link to the phpinfo page would be helpful too.

We use phpversion calls in the installer to detect PDO, but that must be failing for your version.  It doesn't work for all extensions, for example cURL, so maybe we need to change it up.

**Comment by waaghals** [comment]
PDO Driver for MySQL, client library version    5.0.77
PHP Version 5.1.6

I also send you a message with the phpinfo.

**Comment by waaghals** [comment]
I fixed the problem.
I changed Check::ExtensionExists( ''PDO', 'PDO' ); to Check::ExtensionExists( 'pdo', 'PDO' );

Then it gave me the option to download the config.ini because I didn't chmod my config folder. When I did this there was an error output in the config file.(A real php error.)  I forgot to copy the the error so this isn't of much use.

After chmodding my config folder the installation was complete.
Then there was the black page again....
After poking around in my error logs i found that mb_internal_encoding() didn't exist.

So there needs to be an other requirements check for mbstring.
I succesfully installed mbstring now.

but now I'm getting this error:
Fatal error: Call to undefined method Zend_View_Helper_Placeholder_Container::ksort() in /var/www/html/Waaghals/dev/protected/library/Zend/View/Helper/HeadMeta.php on line 382

**Comment by jmhobbs** [comment]
Ok, I've never seen that Zend error before.  Maybe someone else has.

Is that the latest copy of Zend?  I can't remember if you need the full lib or not, I haven't touched the code in a while.  It's weird that Zend is erroring out internally...

I'll patch the installer to check some variants on extension names and for mbstring, thanks for debugging and sharing on that.

**Comment by waaghals** [comment]
The solution lies here http://weierophinney.net/matthew/archives/206-Zend-Framework-1.7.5-Released-Important-Note-Regarding-Zend_View.html

I'm running 2.1.0
