### ISSUE TITLE
After successful install, i couldn't login to admin section

### ISSUE THREAD

**Issue by AdilHoumadi** [eschnou/storytlr#26]
hello, Sorry for my poor english,
I don't know what's happen, i installed the last version of storytlr on my local machine, everything is OK, but when I am trying to login into the dashboard of admin section, i get the same page of login and password and it invite me again to key in my info.
Can you help me please ?
best regards :)

**Comment by eschnou** [comment]
Have you solved your issue ? If not, can you let me know if you see any error messages in the logs (logs/... or php error.log). You can also enale the debug mode to see if you get more details (in config.ini, set deug=1). Thanks !

**Comment by bildlich** [comment]
I have the same issue. I set debug to 1 in config.ini and checked the logs; there is nothing in there.

After logging in I'm being forwarded to the same login form again.

**Comment by ghost** [comment]
maybe same issue in my case:
https://github.com/storytlr/core/issues/closed#issue/29

**Comment by lostfocus** [comment]
It's something with the cookie. http://storytlr/ as domain didn't work, http://storytlr.dev/ did. Did you guys install it on localhost ?

**Comment by eschnou** [comment]
I run an instance on my machine but usually with a domain like storytlr.dev, not sure what caused troubles in your cookies. Thanks for reporting back, I'll close this issue then.
