### ISSUE TITLE
Google Analytics support

### ISSUE THREAD

**Issue by abraham** [eschnou/storytlr#28]
It would be sweet to be able to enter a GA id on the advanced tab and have traffic automatically tracked.

**Comment by jmhobbs** [comment]
You can enter the whole GA code into the "Footer Code" area, none of that is HTML escaped.

Does that work or do you think we should simplify and just have a GA code box?

**Comment by abraham** [comment]
I'm not seeing a "Footer Code" area. Where is that located?

**Comment by jmhobbs** [comment]
Should be at /admin/advanced/, at the very bottom.

**Comment by jmhobbs** [comment]
Oops, looks like that's not merged into core.

Here's the file on my fork:
https://github.com/jmhobbs/storytlr/blob/master/protected/application/admin/controllers/AdvancedController.php

**Comment by abraham** [comment]
Nifty. I'll have a look at it.

**Comment by eschnou** [comment]
Took me two years to finally add this, but hey; better late than never :-) All fixes on the dev branches, a stable release is in the work...
