### ISSUE TITLE
Admin permission denied

### ISSUE THREAD

**Issue by ghost** [eschnou/storytlr#29]
Hi, 

after installing i can login (admin-bar appears in frontend), but i cant access the admin pages, when i visit admin-area following message appears (debug on):

Tsk tsk tsk

It seems you don't have access to this page. If you came here using a bookmarked link, please first login and then try again.

(Access denied for member to resource admin:services with privilege index.)

Thanks for help in advance...

**Comment by eschnou** [comment]
It seems you try to access directly /admin/services, what happen when you simply go to http://yourhost/admin ?

**Comment by ghost** [comment]
Thanks, but i did access myhost.com/storytlr/admin 
same error with myhost.com/storytlr/post etc.

(sorry, pressed the wrong button and closed this issue...)
