### ISSUE TITLE
Update icon for identi.ca & status.net streams

### ISSUE THREAD

**Issue by eschnou** [eschnou/storytlr#3]
Currently the icon used is very old, The logo was updated sometime ago.  A
good place to get the new icon is the breakdance project on launchpad.
/via andrew.wafaa

**Comment by jmhobbs** [comment]
I pulled that a while ago for my custom branch.  Just moved it into develop and sent a pull request.

http://github.com/jmhobbs/storytlr/commit/2afce8eacce0e990a98916c8ef60a84723f3e8a6

**Comment by eschnou** [comment]
I have merged it in develop, so I close this issue.
http://github.com/storytlr/core/commit/2afce8eacce0e990a98916c8ef60a84723f3e8a6
