### ISSUE TITLE
Installation Error - Release 1.0.1

### ISSUE THREAD

**Issue by TheAlexSwan** [eschnou/storytlr#35]
Hey guys, I have downloaded and unpacked storytlr release 1.0.1, uploaded it to my web server, changed permission on those folders but I'm getting the following Error:

Parse error: syntax error, unexpected '{' in /nfs/c05/h02/mnt/73333/domains/mydomain.com/html/story/protected/install/install.php on line 41

Any clue what might be the problem? 

Cheers

**Comment by TheAlexSwan** [comment]
stupid me... php5 wasn't activated for that domain. so problem fixed.

**Comment by jmhobbs** [comment]
Was just about to ask :-)

**Comment by TheAlexSwan** [comment]
:-) Thanks. But I'm experiencing another problem now.

Theme doesn't load with this url: http://www.mydomain.com/story/index.php

But it loads with the following url: http://www.mydomain.com/story/

config ini set to:
web.host=www.mydomain.com
web.path=/story/
web.redirect = 1

Plus I can't load urls like: http://www.mydomain.com/story/admin/design/
Error message says: The requested URL /story/admin/design/ was not found on this server.

The page loads with the following url: http://www.mydomain.com/story/index.php/admin/design/

But the theme doesn't load due to wrong urls obviously.

Not sure whats going on here.

**Comment by TheAlexSwan** [comment]
Oh and the site loads super slow... tried a few other sites on the same server and they are as fast as always. Maybe these two issues are connected to each other.
