### ISSUE TITLE
General slowness of the system

### ISSUE THREAD

**Issue by TheAlexSwan** [eschnou/storytlr#37]
As previously mentioned in another post we are experiencing a really long waiting period before the index.php gets executed. And as long as you wait for that, nothing else gets downloaded from the server. You can see this in firebug. I have tested this on two different servers and two different ISPs. One located in the US and another one located in Germany. Waiting periods vary between 3 and 11 seconds. We have tested other websites that are hosted on the same servers and waiting periods are just a few milliseconds. 
We have also checked Eschnou's personal website with the same result... waiting periods up to 10 seconds. 
I have no idea what to look for or how to fix this. 

Cheers

**Comment by TheAlexSwan** [comment]
Forgot to mention that we are also experiencing  a delay without any sources in place. It's not as bad then but already a few seconds.
Once we add flickr, twitter, youtube and so forth it definitely gets worse. 

Schlingsi

**Comment by TheAlexSwan** [comment]
I've just tested a few of the other self hosted storytlr sites and their speed is totally acceptable. Tried our two sites again as well but they still have that waiting period.

**Comment by eschnou** [comment]
This is not an "issue" but more of a performance tuning discussion, there are a few things that can be done indeed. Could you please post this request on the mailing list, in order to involve more users ? 

http://groups.google.com/group/storytlr-discuss
