### ISSUE TITLE
PHP Setting 'magic_quotes_gpc' should be 'false'.

### ISSUE THREAD

**Issue by coasterfreak** [eschnou/storytlr#42]
If I have an problem installing storytlr. Everything is green except this point:
PHP Setting 'magic_quotes_gpc' should be 'false'.
I set magic_quotes_gpc to Off in my php.ini but it is still not fixed.

**Comment by jmhobbs** [comment]
Hey coasterfreak!

Weird it didn't take.  Did you reload the server configuration?   You can also try changing it in .htaccess, that has worked for me before.

http://php.net/manual/en/security.magicquotes.disabling.php

```
php_flag magic_quotes_gpc Off
```

**Comment by coasterfreak** [comment]
thanks now it works fine

**Comment by vishaltelangre** [comment]
I created a file named php.ini in the directory where storytlr is installed with the content given below:
`magic_quotes_gpc = Off
extension="pdo.so"
extension="pdo_mysql.so"`
And this worked for me!

**Comment by pdoley** [comment]
yap vishaltelangre php.ini solution works...great 

magic_quotes_gpc = Off
extension="pdo.so"
extension="pdo_mysql.so"
