### ISSUE TITLE
"Twitter import" feature is not fetching all tweets

### ISSUE THREAD

**Issue by llagerlof** [eschnou/storytlr#45]
For me, only imported 70 tweets, however I have thousands. Same problem reported in this Google Groups topic: https://groups.google.com/forum/#!topic/storytlr-discuss/9dPFlLYN0VY

**Comment by Noxcivis** [comment]
I have the same issue.  Such a shame.  I really wanted to use Storytlr to show my Tweets.  Storytlr also does not import new Tweets since the initial source connection.

**Comment by eschnou** [comment]
Apologizes for never coming back to you, life has been hectic. I'm now busy catching up on issues and fixing things. A lot has been fixed and merged in the dev branch.

I've updated the twitter integration and it now seems to be able to get 2~3000 tweets. It seems to depend on stuff happening on the twitter backend that I don't really understand. Feedback welcome.

Updates are on the dev branch, will package a stable release asap.
