### ISSUE TITLE
SQL error

### ISSUE THREAD

**Issue by romoseki** [eschnou/storytlr#46]
I'm trying to install Storytlr and have all green on the requirements check, but when I try to configure the sql database I keep getting this

You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '' at line 1

Any thoughts? Would love to start using this!

**Comment by eschnou** [comment]
Apologizes for never coming back to you, life has been hectic. I'm now busy catching up on issues and fixing things. A lot has been fixed and merged in the dev branch.

No clue about this issue. If still relevant, please re-open the issue and add details on your environment/os/etc.
