### ISSUE TITLE
User registration and addtional roles?

### ISSUE THREAD

**Issue by vbk** [eschnou/storytlr#50]
I have just installed the script. I was shocked looking at the awesome look of the website based on the script . Thanks for releasing it as Open-Source script 

User registration :

1) I would like to know if there are possibilities for the users to register and login to make comments. I want them as registered users on my storytlr powered website

WordPress integration :

2) En-ability to make additional admins to control and manage 

If that is not possible, integration with WordPress makes it convenient for us. I love that to be implemented. 

Thank you!

**Comment by vbk** [comment]
I would like to know if there is possibility for point 1 - User registration

**Comment by eschnou** [comment]
Yes, see the FAQ for details on how to setup multi user and open registration.
https://github.com/storytlr/core/wiki/Frequently-Asked-Questions
