### ISSUE TITLE
Possibility to setup Multisite Environment ?

### ISSUE THREAD

**Issue by asshu** [eschnou/storytlr#52]
I went trough every corner of my new installation of the script and everything is working fine. I would like to know if there is a multi-site version available 

As the script is based on former StoryTlr 's hosted service, I think there is a possibility of maintaining a multisite environment with self-hosted installation. Could you please let me know if there is such possibility 

Thank you and will be waiting for any help !

**Comment by eschnou** [comment]
Yes, it is explained in the FAQ here:
https://github.com/storytlr/core/wiki/Frequently-Asked-Questions
