### ISSUE TITLE
Have interactivity content with visitors

### ISSUE THREAD

**Issue by lonniea** [eschnou/storytlr#56]
i own a domain called Cybercrime Stories and ive created this domain in hopes in one day i could find a suitable platform to use for it. I think Storytlr is only 5% away from exactly what im looking for.

It would be awesome if people could logon to http://cybercrime-stories.com and interactively tell the word their online or computer crime stories. At present i've merely thrown on some content about identity theft, however its no where near what i want to go with the site and i haven't done anything more.

Now ive stumbled across Storytlr and its only 5% away from what im looking for!

Keep the look n feel, however id like to have people to report their crime stories. It can be any crime story and i think it would serve as very useful online as well.

So please consider this option and or connect with me. Please!

Cheers

**Comment by lonniea** [comment]
or does the app already have ths capability?

**Comment by eschnou** [comment]
Thanks for your ideas. The best for you would be to put this request on our mailing list, maybe someone wants to help out. This issue tracker isn't really the best place for looking for help. The list is here http://groups.google.com/group/storytlr-discuss

**Comment by lonniea** [comment]
thanks a bunch!
