### ISSUE TITLE
Vimeo plugin is broken - Need to use new API

### ISSUE THREAD

**Issue by brim415** [eschnou/storytlr#58]
This is the error I receive when trying to add a vimeo stream:

2012-03-15T17:56:33+01:00 ERR (3): Exception updating vimeo (35): Vimeo API returned http status 404 for url: http://vimeo.com/api/bcworkshop/clips.php

The username for the account is bcworkshop (http://vimeo.com/bcworkshop)

Anyone have an idea what's wrong or what I'm missing?

**Comment by eschnou** [comment]
Indeed, does not work for me either. It seems vimeo upgraded their API to v2 and stopped supporting the old URLs. This is an issue, a new plugin has to be written for the new API. I'm pretty much swamped these days so I won't look at it anytime soon.

If someone wants to fix this issue, I'll be happy to merge. Send me a pull request !

**Comment by eschnou** [comment]
Apologizes for never coming back to you, life has been hectic. I'm now busy catching up on issues and fixing things. A lot has been fixed and merged in the dev branch.

The Vimeo integration has been fixed on the dev branch. Works like a charm :-)
