### ISSUE TITLE
http://USERMANE.www.web.com

### ISSUE THREAD

**Issue by evakant140** [eschnou/storytlr#59]
Hello, I installed the script and I must say that is really superb! I have a problem enabling the multi-user I create this type of link http://USERMANE.www.web.com/. How do I fix? tnk

**Comment by eschnou** [comment]
Apologizes for never coming back to you, life has been hectic. I'm now busy catching up on issues and fixing things. A lot has been fixed and merged in the dev branch.

I've just tested the multi user and it works fine for me. I'm closing the issue. Please re-open if still a problem for you with more details on your setup.
