### ISSUE TITLE
The news won't update.

### ISSUE THREAD

**Issue by ghost** [eschnou/storytlr#79]
At all. It imports the data once when sources are added and then nothing.

**Comment by eschnou** [comment]
Have you setup a cron job as described in the install instructions?
https://github.com/storytlr/storytlr/wiki/Install%20from%20sources#updating-your-sources

**Comment by ghost** [comment]
Works on x10hosting (CPanel) with /usr/bin/php /home/username/public_html/storytlr/protected/tools/update.php admin
