### ISSUE TITLE
Links to help pages hosted on Google Code should be changed to Github

### ISSUE THREAD

**Issue by eschnou** [eschnou/storytlr#8]
./INSTALL:http://code.google.com/p/storytlr/wiki/Install 
./protected/install/template.phtml:                            <li><a href="http://code.google.com/p/storytlr/wiki/GetStarted">Getting started!</a></li>
./protected/install/template.phtml:                            <li><a href="http://code.google.com/p/storytlr/wiki/WikiHome">Storytlr Wiki</a></li>
./protected/application/public/views/layouts/error.phtml:                    <li><a href="http://code.google.com/p/storytlr/wiki/GettingStarted">Getting started!</a></li>
./protected/application/public/views/layouts/error.phtml:                    <li><a href="http://code.google.com/p/storytlr/wiki/FAQ">Frequently asked questions</a></li>
./protected/application/admin/views/layouts/default.phtml:                    <li><a href="http://code.google.com/p/storytlr/wiki/GetStarted">Getting started!</a></li>
./protected/application/admin/views/layouts/default.phtml:                    <li><a href="http://code.google.com/p/storytlr/wiki/WikiHome">Storytlr Wiki</a></li>
./protected/application/admin/controllers/AdvancedController.php:        $e->setDescription("Fill-in your domain name (e.g. www.johndoe.com) and add a CNAME entry towards this domain (<a href='http://code.google.com/p/storytlr/wiki/CName'>help</a>)");
./protected/application/admin/controllers/AdvancedController.php:        $e->setDescription("Create a disqus web site for the url $url and fill-in its short-name (<a href='http://code.google.com/p/storytlr/wiki/FAQ'>help</a>)");

**Comment by sokai** [comment]
Should be fixed now. See https://github.com/storytlr/core/pull/39

**Comment by jmhobbs** [comment]
Got it pulled in, thanks for the patch.
