### ISSUE TITLE
Index page not show

### ISSUE THREAD

**Issue by dreamepoint** [eschnou/storytlr#80]
http://aagazsocial.org/aagazblog/index.php

get error 
Warning: require_once(Zend/Loader/Autoloader.php) [function.require-once]: failed to open stream: No such file or directory in /home/dreamcab/public_html/aagazsocial.org/aagazblog/protected/application/Bootstrap.php on line 21

Fatal error: require_once() [function.require]: Failed opening required 'Zend/Loader/Autoloader.php'

**Comment by eschnou** [comment]
Indeed, you need to install the Zend library. See issue #66.
