### ISSUE TITLE
XML

### ISSUE THREAD

**Issue by freealise** [eschnou/storytlr#82]
Is it possible to use plain XML instead of XML-RPC?
The PHP configuration on my host does not have that module installed.

They say it could be faster as well (I don't know, I'm not an expert).

**Comment by eschnou** [comment]
No, xml-rpc is used for the 'pingback' between storytlr instances. If you don't need that feature, you could try to comment out the requirement. Just comment this line in the code:
https://github.com/storytlr/storytlr/blob/master/protected/install/install.php#L145

That should do the trick :-)

**Comment by pfefferle** [comment]
Perhaps it is possible to add some fallback funktions to the code... Something like that:

https://github.com/pfefferle/mention-client/blob/master/src/IndieWeb/MentionClient.php#L289
