### ISSUE TITLE
Characters are escaped

### ISSUE THREAD

**Issue by socialmeems** [eschnou/storytlr#88]
Hello there my problem is when i post status or video that contain   ' or "   i also get ( '/ ) Thats why the code didnt work.

http://i.imgur.com/g6ihQMD.png

Please help and sorry for my english .

**Comment by eschnou** [comment]
This is the normal behavior. For security reasons, text is escaped, you cannot put HTML content in a status update. 
- You must choose the 'post' type and put the content in the body
- You can also use a 'video' type and put the content in the 'embed' section

**Comment by socialmeems** [comment]
When i choose post type and type like this eg. " No one " , my post will results as /" No one "/
And when i post via video i got the same error
