### ISSUE TITLE
Twitter API version changed

### ISSUE THREAD

**Issue by lisvane** [eschnou/storytlr#89]
Twitter has updated to version 1.1 for all related api:  See  

https://blog.twitter.com/2013/api-v1-retirement-update

I have found various locations to change the version number in storytlr but it still isn't working 100%.  I am still going through to find more.

A single variable needs to be defined somewhere that can be changed whenever there is an update.

**Comment by eschnou** [comment]
This has been fixed a while ago. Which version of storytlr are you using? The ideal is to use the code from the master branch.

**Comment by lisvane** [comment]
Claims to be version 1.2.0

**Comment by lisvane** [comment]
Files dated 20 Jan 2013.  The latest version has files dated 25 Mar 2013.  Can I copy certain ones over rather than do a complete reinstall.  The earlier files were loaded via Softaculous.

**Comment by eschnou** [comment]
Yes, unpacking a new release and overwriting an old one should work. Although I'm not sure how softaculous is managing the files. Thus, best to do a backup of the files/foder before you attempt anything.
