### ISSUE TITLE
admin panel

### ISSUE THREAD

**Issue by ghost** [eschnou/storytlr#92]
hello, today i finally installed storytlr succesfull on my vps..
However, i cannot find admin panel ?? I downloaded latest version.

**Comment by ghost** [comment]
mydomain.com/admin does not exist.

**Comment by ghost** [comment]
Installation went great. Front page working fine

**Comment by eschnou** [comment]
Do you still have the problem? This is usually due to a mis-configured .htaccess. You probably have a setting in your VPS that need sto be checked to enable the .htaccess file which is in the root.

Or you can configure the same rules via your VPS control panel.

**Comment by JessicaPuebla** [comment]
Help! Now I have this same problem. What can I do?

In #95 you commented 

> I really have no clue on how to setup on windows. But for the Zend framework, you can simply put it in the storytlr/protected/library/ folder. So you should have something like:
> /storytlr/protected/library/Zend/ 

I do not have this folder. Why?
