### ISSUE TITLE
Cannot link google into storytlr

### ISSUE THREAD

**Issue by ZoomyCat** [eschnou/storytlr#93]
Storytlr correctly syncs up my github and youtube but does not take the ID number to import the data from google+.

I recieve this error:

There was an error while importing the data. Please doublecheck your import configuration and try again later. Let us know if this problem persists.
Error was: Google+ did not return any result.

**Comment by ZoomyCat** [comment]
I think a more applicable option than the current one would be to have the person give the entire URL to their profile posts and parse the needed information from that URL.

**Comment by eschnou** [comment]
I think the Google+ integration is just broken. It was based on an old hacky API which is now deprecated. I haven't looked at fixing it but if you want to give it a try, I'm happy to help out and accept a pull request.

**Comment by ZoomyCat** [comment]
Nah. I can always just post the links of things I say at the originating source onto G+. That is probably the better option anyways.
