### ISSUE TITLE
Github not renewing commits.

### ISSUE THREAD

**Issue by ZoomyCat** [eschnou/storytlr#94]
The imports synced initially a few months into the past. Great. New commits are not showing up as existing though.

**Comment by eschnou** [comment]
No issues for me, my commits keep on being syndicated. Do you have the problem only with Github content, or with all other feeds ? Can you try executing the update command by hand and look for error messages ?

**Comment by ZoomyCat** [comment]
eschnou It is happening with both devs on each of our github pages, it is from the same location so a config file may be a skew but that is doubtful. I have not tried syndicating from another site. How do I run the update command by hand and where would the errors be located?

**Comment by ZoomyCat** [comment]
For the most part I choose storytlr because it could syndicate from github which made it easier to track what others on the team had done and potentially made reviewing changes done by groups easier.

Provided this functionality works correctly I plan on having every member of the core development team have storytlr blogs hosted by me because it just works efficiently. When it works anyways ;)

**Comment by eschnou** [comment]
Nice use case ! I assume you simply do not have the cron job in place to perform the updates, hence the issue. It is documented here: 
https://github.com/storytlr/storytlr/wiki/Install%20from%20sources#updating-your-sources

Let me know how it works!

**Comment by ZoomyCat** [comment]
Does <username> relate to the username you log in with or the database username?

**Comment by eschnou** [comment]
If you don't pass arguments, it updates all sources for all users. You can pass an optional [username] and [source] argument to update a single user, or even a single source for a single user.

**Comment by ZoomyCat** [comment]
I tried passing without a argument and it says it states it requires the user argument. Otherwise it appears to do nothing. It paused the first time but did nothing.

**Comment by ZoomyCat** [comment]
I had passed it the name of the user that I login with, Would this be the correct parameter?

**Comment by eschnou** [comment]
Yup, if admin is your username, it should work. As well as without parameters (should fetch for all users).

Which version of storytlr are you using ? Best is to take the last one from github master branch, since I haven't repackaged a proper release in a while.

**Comment by ZoomyCat** [comment]
Ah. I was using a release that was pushed through from the host I am using. I really have no idea. Do you think it would be beneficial to put out a proper release schedule so people that do use that software to keep track and maintain their web software can get updates easier?

**Comment by ZoomyCat** [comment]
I know I would appreciate if you did that ;)

**Comment by eschnou** [comment]
Well, this project is really no more in active development. I do my best to fix issues when they arise on the master branch, and to support users who post issues here but that's pretty much what I can do. I'll eventually package a new release when I get the time... you can complain to the softaculous/whatever guys, maybe they'll take the time to update their package !

**Comment by ZoomyCat** [comment]
Maybe so. It is disappointing to hear that you do not have the time to actively develop the project. The software really is unique among microblogs.
