### ISSUE TITLE
20 times installed: NO work!

### ISSUE THREAD

**Issue by quaxth** [eschnou/storytlr#95]
As the title say's!

The main problem I facing is that I could not login as admin. Used custom name and password: didn't work! used the given username and password (admin/password): didn't work! 
![st1](https://cloud.githubusercontent.com/assets/8458500/3934337/3c9696d4-248a-11e4-915a-01624afc8c5f.jpg)
![st2](https://cloud.githubusercontent.com/assets/8458500/3934339/44424d7e-248a-11e4-89c3-993b1d88b92a.jpg)
![st3](https://cloud.githubusercontent.com/assets/8458500/3934341/472461c6-248a-11e4-9c70-75de00acafbb.jpg)
 How to get the Storytlr to work?

I use AMPPS from Softaculous on my Desktop with Apache, MySQL, PHP and others! 

Thanks for any help to get me in as admin so I could start working with that apps.

**Comment by eschnou** [comment]
I have no clue about the Softaculous installer. Did you try installing manually ?

**Comment by quaxth** [comment]
Hello Laurent,

Thanks for answer.

I now had try to in stall Storyltr manually om AMPPS, running with Apache2, PHP5, MySQL and others and get the following error:

This is an test installation on my ndesktop while the final install will be on an hosted server at http://freehosting2.com which used cPanel. 
The installed OS is some Linux with:

Now, it seems to be that I need to install the Zend Framwork on my desktop and I think on the hosted server as well?! 

Could yopu mplease give me some guideline of How To......? Thanks a lot.

By the way, I informed and reported the problem of the not working instllation to Sofataculous already and they will check their script, which will need some time.

Thanks a lot for your help.

Monday, August 18, 2014, 6:20:47 PM, you wrote:

I have no clue about the Softaculous installer. Did you try installing manually ? 
—
Reply to this email directly or view it on GitHub.

## 

Best regards,
 Gmail                            mailto:reimar.pcinfo@gmail.com

**Comment by eschnou** [comment]
Yes, you need some dependencies. They are listed here:
https://github.com/storytlr/storytlr/wiki/Install%20from%20sources

For the Zend Framework, you must download the latest release in version 1. I think this is the link:
https://packages.zendframework.com/releases/ZendFramework-1.12.7/ZendFramework-1.12.7-minimal.tar.gz

Unpack it somewhere and add the library in your php path.

**Comment by quaxth** [comment]
Thanks.
I'm a noob and need an advice at which file I've to add the path for Zend Framework. As I installed it, I was getting the latest version 2.3.2. Do I need that exact version you posted?
Before I install that apps on the hosted space, I like to test on my desktop first, that's why I use AMPPS from Softaculous. And there although I found the Storyltr apps! On my desktop I use Windows 8.1 Pro and not linux. AMPPS is similar to XAMPP etc. and has Apache2, PHP 5.x 3 versions and all other required modules etc., the only one which isn't auto installed is Zend Framework. The Script an AMPPS is just the latest version and integrates correctly with AMPPS while installing. 
The final install will be on Linux on the hosted space, I use freehosting2.com because it let me although use the .tk domains, which many other free hosters didn't allowing. Even their Mail Servers let me setup to my needs.
Storyltr and what I've read about it, seems to exactly what I'm looking for and need. And Yes, I really like to get it to work and see it will do what it's promise. 

I really appreciate any help, thanks a lot.

**Comment by eschnou** [comment]
Indeed, you need version 1.something, not 2.something. We are not compatible with ZF2. I've updated the wiki to make this more clear.

You closed the issue, so I assume it now works ? Anyway, feel free to reopen a ticket if you have other issues.

**Comment by quaxth** [comment]
Thanks for the info.

And sorry, I don't know how Git is working, never used it. The closure were just by mistakes.

And NO, it's not working yet. Although the Script Dep at Softaculous is working on that issue because they facing the same problem. Now I'll uninstall that new ZF2.x and install the old one. Could please me an simple and detailed hint of How To.....? I really don't know what file at what location I've to change and/or add some path etc. please help out with that. 

I'm now 'playing' a week with Storyltr around and had even not once be able to open the Admin page for to start and configure. 

Thanks a lot for any help.

**Comment by eschnou** [comment]
I really have no clue on how to setup on windows. But for the Zend framework, you can simply put it in the storytlr/protected/library/ folder. So you should have something like:

./storytlr/protected/library/Zend/

**Comment by quaxth** [comment]
Thanks. I'll try that.

Let you know tomorrow how it works, it's already near 22:00h in Thailand and I've to wake up at 5am!

Thanks alot for your help and best regards from Thailand.

**Comment by dreamerofwords** [comment]
I have set up Storytlr on my website. My host uses cPanel and Windows 7. I set it up from Softalicious with no problems. Accessed my admin easily. Able to make necessary changes and it's nice and easy to work with. Let me know if I can help.
