### ISSUE TITLE
Unable to view webpage without logging in

### ISSUE THREAD

**Issue by dreamerofwords** [eschnou/storytlr#96]
This is the screen I get every time, even after clearing cache multiple time:

![11-28-2014 4-04-00 pm](https://cloud.githubusercontent.com/assets/9994837/5232979/6cf4a74a-7718-11e4-8ea6-2efc68e2caa9.png)

What should I do to correct this asap?

**Comment by eschnou** [comment]
Sorry I didn't have time to look into this. Glad you have solved it. Can you share what the issue was, so it could help other users having the same issue ? Thanks !
