### ISSUE TITLE
Project Dead?

### ISSUE THREAD

**Issue by kreativmind** [eschnou/storytlr#97]
I am assuming this project is no longer under development?

**Comment by eschnou** [comment]
This project is no longer in 'active development'. I'm however trying to fix key bugs when they arise. I'm also happy to review and merge pull request. It is still being used as a personal blog by many users. My own site is still running storytlr: http://eschnou.com

**Comment by kreativmind** [comment]
Any particular reason you aren't maintaining it for active dev? Seems to be worthy of keeping alive. Sorry for such a late reply.

**Comment by kreativmind** [comment]
I started a new issue. Please look at it when you can and let me know. My email is jeremy.monroe@live.com. This platform looks quite intriguing and I think it's what I am looking for to use.

**Comment by eschnou** [comment]
It keeps on working mostly fine for me (see http://eschnou.com) and I'm swamped by my new startup, so I don't have time to work on this. I'm happy to merge pull requests if any.

**Comment by eschnou** [comment]
Can you open a new issue for the twitter problem ? Are you running the latest code from github or something installed by scriptaculous or similar service ?

**Comment by kreativmind** [comment]
I understand you have priorities. Sorry for being bothersome. Thank you
