### ISSUE TITLE
Enabling multiuser

### ISSUE THREAD

**Issue by kreativmind** [eschnou/storytlr#98]
I am not sure if this has anything to do with it or not, but I have ; out the line as stated in the instructions. I have the site installed and I am on the status page. I type in a status and enter some tags. I click post button and it brings me to admin.mysite.com and I get the following

This webpage is not available

ERR_NAME_NOT_RESOLVED

The dns lookup has failed.

I don't have a subdomain setup for admin.mysite.com//entry/the-title-of-my-entry-1-2.html. I just have the www and enabled multiuser.

Any ideas? Thanks!

**Comment by kreativmind** [comment]
Wanted to update you and let you know if I remove the ; from the line in the config.ini file, my post is successful. Any ideas?

**Comment by kreativmind** [comment]
Another issue I am having is that I cannot use the Sign in with Twitter option. I have created another app in my Twitter dev account and entered the keys in the config.ini file and saved. It keeps telling me the following message: Could not connect to Twitter. Refresh the page or try again later.

**Comment by eschnou** [comment]
In multiuser mode, all users have their own subdomain: admin.example.com, johndoe.example.com, etc. For this to work, you need a wildcard dns entry that points all subdomains to the storytlr server, or you must manually add one dns entry per user.

**Comment by kreativmind** [comment]
I will try this and see if it works. Not sure why the url is putting in 2 //'s in the url when I click on the post button but will see what happens after I add the wildcard dns entry.

**Comment by kreativmind** [comment]
404 Not Found
The server can not find the requested page:

admin.mysite.com//entry/testing-out-multiuser-configuration-1-7.html (port 80)
Please forward this error screen to admin.mysite.com's WebMaster.

**Comment by kreativmind** [comment]
I have the wildcard dns entry setup but stil getting the same message above with the url getting the 2 //. I guess this isn't going to get resolved as I see that StoryTlr is not going to get much attention any longer. Sorry to bother you.
